Create completion
orbisgis/orbisrcp pull request #69
Opened 2022-02-21 09:17 UTC by adrbessy

Build the list of the completion proposals in an assistant pop up.
This list is generated thanks to the services of the Groovy Langage Server project.

2022-02-21 09:30 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +				    System.out.println("currWord : " + currWord);
Please avoid `println()`usage.

2022-02-21 09:31 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +				String LANGUAGE_GROOVY = "groovy";
For magic constants, you better declare it as `private static final` variable in your class instead of in your method body.

2022-02-21 09:39 UTC, SPalominos requested changes

2022-02-21 09:39 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +				    System.out.println("currWord : " + currWord);
Please avoid `println()`usage.

2022-02-21 09:39 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +				String LANGUAGE_GROOVY = "groovy";
For magic constants, you better declare it as `private static final` variable in your class instead of in your method body.

2022-02-21 09:39 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +		        Path workspaceRoot = Paths.get(System.getProperty("user.dir")).resolve("./build/test_workspace/");
Can you use the DBeaver user workspace instead of a user folder ?

2022-02-21 09:39 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +		        Path filePath = workspaceRoot.resolve("Completion.groovy");
You should get the current groovy script instead of a static file.

2022-02-21 09:39 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +					e.printStackTrace();
Please log the `Exception` using a `Logger` like `LOGGER.error("Error on getting the completion service result.", e);`

2022-02-21 09:39 UTC, SPalominos commented on plugins/org.orbisgis.groovyeditor/src/org/orbisgis/ui/editors/groovy/GroovyCompletionProcessor.java
> +		    	return null;
Same here, log the exception

2022-02-21 09:41 UTC, SPalominos commented
You PR failed building, it is because you haven't included the dependencies `libs/groovy-language-server-master-all.jar` and  `libs/org.eclipse.lsp4j-0.13.0-SNAPSHOT.jar` in the `libs` folder.

2022-02-21 10:51 UTC, adrbessy commented
![completion](https://user-images.githubusercontent.com/7083184/154940870-cbcaeb35-1903-400d-b89d-0bd67ff0676f.png)
![variable_completion](https://user-images.githubusercontent.com/7083184/154940884-50a6ba20-2fb3-4c73-8785-025114bc2a45.png)

2022-02-21 11:00 UTC, ebocher commented
Can you add a completion example with a grabed library, i.e demat ?

2022-02-28 15:41 UTC, ebocher commented
Is it possible to set in the issue #51,  the feature you are working on ?

2022-03-02 10:39 UTC, SPalominos approved these changes

2022-03-02 10:41 UTC, merged